// sesion08/vue-todo-list/src/components/TodoItem.vue
<template>
  <div>
      <input
        type="checkbox"
        v-bind:checked="todo.completed"
        v-on:change="$emit('mark-complete', todo.id)"
        />
        <label>{{todo.title}}</label>
        <button
          v-on:click="$emit('delete-todo', todo.id)"
        ></button>
  </div>
</template>

<script>
export default {
    name: 'TodoItem',
    props: ["todo"]
}
</script>

<style>
  li.completed label {
      text-decoration: line-through;
  }
</style>

// sesion12/react-todo-list/src/components/TodoItem.js
import React, { Component } from 'react';

export default class TodoItem extends Component {

  componentStyle = () => {
    return {
      background: 'lightsteelblue',
      padding: '9px',
      boderBottom: '1.5 solid #ccc',
      textDecoration: this.props.todo.completed ? 'line-through' : 'none'
    }
  }

  render() {
    return (
      <div style={this.componentStyle()}>
        <input
          type="checkbox"
          onChange={this.props.markComplete.bind(this, this.props.todo.id)}
        />
        <p>{this.props.todo.title}</p>
      </div>
    );
  }
}
